import HeaderLogOut from "@/components/HeaderLogOut";
import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import HeaderLogged from "@/components/HeaderLogged";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Your Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = createServerComponentClient({ cookies });
  const session = await supabase.auth.getSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        {session.data.session !== null ? <HeaderLogged /> : <HeaderLogOut />}
        {children}
      </body>
    </html>
  );
}
